# Generated by Django 4.1 on 2022-09-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv_file',
            new_name='CSV',
        ),
    ]
